version: '3.8'

services:
  mysql:
    image: mysql:8.0.27
    restart: always
    environment:
      MYSQL_DATABASE: myhotldb
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  spring-jpa-app:
    build: .
    ports:
      - "8080:8081"
    depends_on:
      - mysql
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/myhotldb
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root

volumes:
  mysql_data:
